### ISSUE TITLE
localhost 8080 not sending data

### ISSUE THREAD

**Issue by tonyern** [cybercommons/cybercommons#7]
After building and deploying Cybercommons with Docker-Compose, when visiting local:8080 link, local:8080 did not send any data. I can see that the port is open but Cybercommons didn't send any data.

**Comment by tdpearson** [comment]
Try accessing http://localhost:8080 or http://127.0.0.1:8080 after launching cybercommons.

**Comment by tdpearson** [comment]
@tonyern Did the above suggestions make any difference with accessing the application?

**Comment by tonyern** [comment]
I had to use this repo to run it. https://github.com/oulib-datacatalog/cybercommons
